image: archlinux
packages:
    - rsync
    - elixir
secrets:
    - 9a147ee3-2828-4ec6-84b5-7f1cca42d9b1
    - 5b7a28c5-476f-4b14-b40c-8e5567b9f188
sources:
    - git+ssh://git@git.sr.ht/~mlb/linkhut
tasks:
    - bootstrap: |
        cd linkhut
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
    - build-docs: |
        cd linkhut
        mix docs --formatter html
    - upload-docs: |
        rsync -r /home/build/linkhut/doc/* deploy@mlb.st:/var/www/linkhut-docs/
